---
- hosts: web01
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install Python
      apt:
        name: python3
        state: present

    - name: Download Jenkins repository key
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        dest: /tmp/jenkins.io.key

    - name: Add Jenkins repository key
      apt_key:
        file: /tmp/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Update apt cache after adding Jenkins repository
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: check jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

